# Generated by Django 5.2.11 on 2026-02-27 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='사용자가 입력한 고민 혹은 질문에 대한 원문')),
                ('response_json', models.JSONField(help_text='모델이 반환한 구조화 응답')),
                ('model', models.CharField(default='gpt-5-chat-latest', help_text='사용된 모델 이름', max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='모델 응답에 걸린 시간(밀리초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='요청을 보낸 사용자(관리자)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
