# Generated by Django 5.2.11 on 2026-02-27 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_chatlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='response_json',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='model',
            field=models.CharField(default='gpt-5-chat-latest', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
